package perlin.render;

/**
 * Class to render a matrix generated by Perlin noise.
 * @author nordryd
 */
public class PerlinRenderer
{
	public static void renderPerlinMatrix(int height, int width) {
		
	}
}
